<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2k4gb2f\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2k4gb2f/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container2k4gb2f.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container2k4gb2f\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container2k4gb2f\appAppKernelProdContainer([
    'container.build_hash' => '2k4gb2f',
    'container.build_id' => '9be0bb0f',
    'container.build_time' => 1730326709,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2k4gb2f');
