<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqgvxzEadaI4v+B9O0w/B'."\n".'+BtRuUxOyRHpIF3k18tjzh0WALb3xai+Ym5CFhGZ8vUgNEHNBfK4NSZYuO1QB67Y'."\n".'j4TD8DggmPpq8Fq576M+P5BsHhhu53/m4UcgGLL+8AEgLlslWz03VwPUNaM4akEU'."\n".'dfp9zE8mWj9DIstGTJjwr3Bca8RWszsi/90L5UYqvMfhoV86TtuMuJRxL77rzBqe'."\n".'ReziL44OriFdyfmGqm+ZI88V/m1OWpHqjougDTOoLF4ANCe8RYnZ1BdtAc/+drKA'."\n".'7KBmrKZGyvKvMS5l3VfDbFdKtJB0xhliACVUtUxRYsTE+HEOkvnJEfD6jIk3I8N6'."\n".'fwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
