<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7aGLrjV\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7aGLrjV/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container7aGLrjV.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container7aGLrjV\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container7aGLrjV\appAppKernelProdContainer([
    'container.build_hash' => '7aGLrjV',
    'container.build_id' => '6ee5ee0a',
    'container.build_time' => 1732227705,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7aGLrjV');
