<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0o3KLvW\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0o3KLvW/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container0o3KLvW.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container0o3KLvW\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container0o3KLvW\appAppKernelProdContainer([
    'container.build_hash' => '0o3KLvW',
    'container.build_id' => '5e4af9f3',
    'container.build_time' => 1732974059,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0o3KLvW');
