<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKzpOgvG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKzpOgvG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKzpOgvG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKzpOgvG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKzpOgvG\appAppKernelProdContainer([
    'container.build_hash' => 'KzpOgvG',
    'container.build_id' => '83dc0f91',
    'container.build_time' => 1732225097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKzpOgvG');
