<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSpHMRcE\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSpHMRcE/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSpHMRcE.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSpHMRcE\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerSpHMRcE\appAppKernelDevDebugContainer([
    'container.build_hash' => 'SpHMRcE',
    'container.build_id' => '0870f046',
    'container.build_time' => 1732740796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSpHMRcE');
