<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container89JYLxJ\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container89JYLxJ/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container89JYLxJ.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container89JYLxJ\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container89JYLxJ\appAppKernelDevDebugContainer([
    'container.build_hash' => '89JYLxJ',
    'container.build_id' => 'be31f956',
    'container.build_time' => 1731546890,
], __DIR__.\DIRECTORY_SEPARATOR.'Container89JYLxJ');
